#!/bin/bash
# Deploy script for HEDTools
# Copy the matlab folder into a folder named HEDTools[version_number] and create zip file and put it in the EEGLABPlugin folder
NAME="HEDTools$1"
echo $NAME
cp -r ./HEDTools $NAME
zip -r "$NAME.zip" $NAME
rm -rf ./$NAME
mv ./"$NAME.zip" ./EEGLABPlugin
