function [fMap, canceled, taggedCombinedFields] = selectFieldAndTag(initialfMap, varargin)
varargin = varargin{:};
fMap = initialfMap;
taggedCombinedFields = {};
[~, primaryField] = getkeyvalue('PrimaryEventField',varargin{:});
% Create the button panel at the bottom of the GUI
f = figure('Position',[30 350 300 450],...
             'Color', [.66 .76 1], ...
             'MenuBar','none',...
             'NumberTitle','off',...
             'Name', 'Select field to use for tagging');
uicontrol('Parent', f,...
          'Style','text',...
          'string', 'Select a field then click "Tag"',...
          'max', 2, 'min', 0,...
          'HorizontalAlignment','center',...
          'Position', [10 408 280 40],...
          'BackgroundColor',[.66 .76 1],...
          'ForegroundColor', [0 0 .4],...
          'FontSize', 14);

fields = fMap.getFields();
uicontrol(f,...
          'style','listbox',...
          'HorizontalAlignment','left',...
          'string', fields,...
          'Position', [10 124 280 300],...
          'FontSize',14,...
          'tag','listboxCB');
      %'min', 0, 'max', 2,... % for multiple select field --> combinations
uicontrol('Parent',f,...
        'style','pushbutton',...
        'string', 'Tag',...
        'Position',[10 95 60 20],...
        'FontSize',12,...
        'Callback', {@tagCallback},...
        'tag','TagBtn');
uicontrol('parent',f,...
      'style','text',...
      'string','Primary field:',...
      'position',[10 70 75 20],...
      'HorizontalAlignment','left',...
      'BackgroundColor',[.66 .76 1],...
      'ForegroundColor', [0 0 .4],...
      'FontSize', 12);
uicontrol('parent',f,...
      'style','popupmenu',...
      'string',fields,...
      'Value', find(cellfun(@(x) ~isempty(x),strfind(fields,primaryField))),... % set value to default primary field
      'position',[80 70 100 20],...
      'tag','primaryFieldBox'); 
uicontrol('Parent', f,...
      'Style','text',...
      'string', 'Click "Ok" to continue when finish tagging',...
      'max', 2, 'min', 0,...
      'HorizontalAlignment','left',...
      'Position', [10 40 280 20],...
      'BackgroundColor',[.66 .76 1],...
      'ForegroundColor', [0 0 .4],...
      'FontSize', 14);
uicontrol('Parent',f,...
        'style','pushbutton',...
        'string', 'Cancel',...
        'Position',[160 10 60 20],...
        'FontSize',12,...
        'Callback', {@fieldSelectCloseCallback, f, initialfMap},...
        'tag','CancelBtn');
uicontrol('Parent',f,...
        'style','pushbutton',...
        'string', 'Ok',...
        'Position',[230 10 60 20],...
        'FontSize', 12,...
        'Callback', {@fieldSelectCloseCallback, f, initialfMap},...
        'tag', 'OKBtn');  
uiwait(f);    
     %% Callback for button "Tag"
    % Tag selected field. Can be repeated while select field window is
    % still on and fMap (shared across tagging sessions) will keep being updated
    function tagCallback(src, event) 
        % disable all buttons
        set(findobj('tag','primaryFieldBox'),'Enable','off');
        set(findobj('tag','listboxCB'),'Enable','off');
        set(findobj('tag','TagBtn'),'Enable','off');
        set(findobj('tag','CancelBtn'),'Enable','off');
        set(findobj('tag','OKBtn'),'Enable','off');
        % set primary field
        primaryFieldBox = findobj('Tag', 'primaryFieldBox');
        primaryFieldIdx = get(primaryFieldBox,'Value');
        fieldsInBox = get(primaryFieldBox, 'String');
        selectedField = fieldsInBox{primaryFieldIdx};
        if (fMap.isField(selectedField)) 
            fMap.setPrimaryMap(selectedField);
        else
            error("Error in pop_tageeg: selected primary field is not in fMap");
        end
%         p.PrimaryEventField = selectedField;
        % prepare input arguments
        selected = get(findobj('Tag', 'listboxCB'),'Value');
        mainOptions = get(findobj('Tag','listboxCB'),'string');
        if numel(selected) == 1
            args = {'EventFieldsToIgnore', setdiff(mainOptions,mainOptions{selected})};
        else
            args = {'CombinedFieldsToTag', join(mainOptions(selected),'+')};
            taggedCombinedFields = [taggedCombinedFields{:}, join(mainOptions(selected),'+')];
        end
        editmapsInputArgs = [getkeyvalue({'HedExtensionsAllowed', 'PreserveTagPrefixes'}, ...
                varargin{:}) args];
        % call CTAGGER
        [fMap, canceled] = editmaps(fMap, editmapsInputArgs{:});
        % finish tagging, return control to fieldSelectWindow
        set(findobj('Tag','listboxCB'),'Enable','on');
        set(findobj('Tag','TagBtn'),'Enable','on');
        set(findobj('tag','CancelBtn'),'Enable','on');
        set(findobj('tag','OKBtn'),'Enable','on');
    end % tagFieldCallback

    %% Callback for closing buttons in fieldSelectWindow
    % Close fieldSelectWindow
    % if Cancel button was clicked, restore orignial fMap
    function fieldSelectCloseCallback(src, event, f, initialfMap)
        if isfield(src,'String') && strcmp(src.String,'Cancel')
            canceled = true;
            fMap = initialfMap;
            close(f);
        else
            close(f);
        end
    end % fieldSelectCloseCallback
end